package com.example.aljuneidi.salesman

open class salesman(var SalesmanNumber:Int,
                   var RouteNameEnglish:String,
                   var RouteNameArabic:String,
                   var SalesmanNameEng:String,
                   var SalesmanNameArabic:String,
                   var SalesmanUserID:Int,
                   var SalesmanPassword:String,
                   var EnableSalesOperations:String,
                   var EnableReturns:String,
                   var EnableDueInvCollection:String,
                   var EnableDistribution:String,
                   var EnableShelving:String,
                   var EnablePricing:String,
                   var EnableFixtures:String,
                   var MasterKeyBarcode:String,
                   var NextCashDocNumber:String,
                   var NextCreditDocNumber:String,
                   var NextReturnDocNumber:String,
                   var NextReceiptDocNumber:String,
                   var NextFixtureDocNumber:String,
                   var NextLoadDocNumber:String,
                   var NextFreeVoucherDocNumber:String,
                   var NextDepositDocNumber:String,
                   var GroupID:String,
                   var TodayVisitsTarget:String,
                   var MonthVisitsTarget:String,
                   var MonthSalesTargetValue:String,
                   var MTDSalesValue:String,
                   var VanStoreBarcode:String,
                   var StoreID:String,
                   var NumOfItemsPerClass:String,
                   var TodayNumberOfVisits:String,
                   var TodayNumberOfEffectiveVisits:String,
                   var NumberOfCashSales:String,
                   var NumberOfCreditSales:String,
                   var NumberOfReceipts:String,
                   var NumberOfCollections:String,
                   var NumberOfReturns:String,
                   var NumberOfCashReturns:String,
                   var NumberOfCheques:String,
                   var CashSalesValue:String,
                   var CreditSalesValue:String,
                   var CashReturnsValue:String,
                   var CreditCollectionValue:String,
                   var TotPocketCashMoney:String,
                   var TotPocketChequeMoney:String,
                   var EditingALoadOrder:String,
                   var ScannedStartOfJourney:String,
                   var StartMovTimeInSec:String,
                   var EndMovTimeInSec:String,
                   var CustTimeInSec:String,
                   var BreakTimeInSec:String,
                   var EnablePrinting:String,
                   var SupervisorID:String,
                   var SalesAreaManagerID:String,
                   var SalesManagerID:String,
                   var OrderAllowed:Int,
                   var NextOrderNumber:String,
                   var NumberOfOrderTaking:String,
                   var OrderTakingValue:String,
                   var NextFactoryReturnsSerial:String,
                   var NextReturnsCheckSerial:String,
                   var NextSuggestedOrderSerial:String,
                   var NextFOCSerialNumber:String,
                   var NextPaymentVoucherSerial:String,
                   var WHTransactionNumber:String) {




}